# Generated by Django 4.0.4 on 2022-05-03 21:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_sm',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/avatars/sm/', verbose_name='avatar'),
        ),
    ]
